#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_id=anto-odin
mod_name=AntoOdin
mod_description=Additions to Odin for niche wants
mod_version=0.3.1-r1
maven_group=com.anto
archives_base_name=anto-odin
# Mod Dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_api_version=0.151.0+26.1.2
modmenu_version=18.0.0-beta.1
devauth_version=1.2.2
commodore_version=1.0.1
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
minecraft_lwjgl_version=3.4.1

odin_version=cC7YBIsC
